// RDP FAIL REASON
const ROOM_FULL = "ROOM_FULL";
const ROOM_AVAILABLE = "ROOM_AVAILABLE";
const ROOM_UNAVAILABLE = "ROOM_UNAVAILABLE";
const USER_ALREADY_JOIN = "USER_ALREADY_JOIN";

module.exports = {
    ROOM_FULL,
    ROOM_AVAILABLE,
    ROOM_UNAVAILABLE,
    USER_ALREADY_JOIN
}